version: "3.9"
services:
  app_php:
    build:
      context: .docker
      dockerfile: Dockerfile
    image: app/php
    container_name: app_php
    ports:
      - 8080:80
    volumes:
      - ./src/:/var/www/html
